controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

joint_trajectory_controller:
  ros__parameters:
    joints:
      # Rev Link R
      - sphere_caudal_fin_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity